language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
env:
  - WITH_CONSTRAINTS=yes WITH_NUMPY=yes
  - WITH_CONSTRAINTS=yes WITH_NUMPY=no
  - WITH_CONSTRAINTS=no  WITH_NUMPY=yes
  - WITH_CONSTRAINTS=no  WITH_NUMPY=no
install:
  - pip install unittest2
  - if [[ $WITH_CONSTRAINTS == 'yes' ]]; then pip install -r constraints.txt; fi
script:
  - python run_tests.py
