language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py2-CONS-NUMPY
    - python: "3.5"
      env: TOXENV=py35-CONS-NUMPY

    - python: "2.7"
      env: TOXENV=py2-NOCONS-NUMPY
    - python: "3.5"
      env: TOXENV=py35-NOCONS-NUMPY

    - python: "2.7"
      env: TOXENV=py2-CONS-NONUMPY
    - python: "3.5"
      env: TOXENV=py35-CONS-NONUMPY

    - python: "2.7"
      env: TOXENV=py2-NOCONS-NONUMPY
    - python: "3.5"
      env: TOXENV=py35-NOCONS-NONUMPY
    - python: "3.7-dev"
      env: TOXENV=py37-NOCONS-NONUMPY
    - python: pypy
      env: TOXENV=pypy-NOCONS-NONUMPY

    - python: "3.7-dev"
      env: TOXENV=flake8
install:
  - pip install tox
script:
  - tox
